version: '3.7'

services:
  wordpress:
    image: wordpress
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: mysecurepassword

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: mysecurepassword
