version: '3.7'

services:
  wordpress:
    image: wordpress
    depends_on:
      - mysql
    labels:
      - "traefik.frontend.rule=Host:localhost"
      - "traefik.docker.network=proxy"
    networks:
      - proxy
      - default
    environment:
      WORDPRESS_DB_PASSWORD: mysecurepassword
    volumes:
      - wp:/var/www/html

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: mysecurepassword
    volumes:
      - db:/var/lib/mysql

networks:
  proxy:
    external: true

volumes:
  wp:
    name: wp
    driver: local
  db:
    name: db
    driver: local
